// apps/web/src/components/ui/CommandPalette.tsx
import {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type HTMLAttributes,
  type InputHTMLAttributes,
  type KeyboardEvent,
  type ReactNode,
  type RefObject,
} from "react";
import { createPortal } from "react-dom";
import {
  useCollection,
  useCollectionItem,
  useComposedRefs,
  useControllableState,
  useIsomorphicLayoutEffect,
  usePresence,
  type Collection,
  type CollectionRecord,
} from "@defied-labs/prism-react";
import {
  hideOthers,
  lockScroll,
  nextIndex,
  onDismiss,
  slotClass,
  trapFocus,
  variantData,
  type StyleSlots,
} from "@defied-labs/prism-core";
import {
  filterCommands,
  firstEnabled,
  isApplePlatform,
  matchesCommand,
  matchesShortcut,
  isTypingShortcut,
  parseShortcut,
  type CommandItem as CommandItemData,
} from "@defied-labs/prism-core/components/command-palette";
import { tailwindSlots } from "@defied-labs/prism-core/tailwind";

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = tailwindSlots({
  "root": {
    "base": "",
    "variants": {}
  },
  "overlay": {
    "base": "fixed inset-0 z-(--prism-z-overlay) bg-prism-overlay [animation:prism-fade-in_var(--prism-duration-normal)_var(--prism-easing-standard)] data-[state=closed]:[animation:prism-fade-out_var(--prism-duration-fast)_var(--prism-easing-exit)_forwards]",
    "variants": {}
  },
  "content": {
    "base": "fixed z-(--prism-z-modal) [top:15vh] [left:0] [right:0] [margin-inline:auto] box-border [width:calc(100vw_-_2_*_var(--prism-space-4))] [max-height:70vh] flex flex-col overflow-hidden rounded-prism-lg [border-width:1px] border-solid border-prism-border bg-prism-bg text-prism-fg shadow-prism-lg font-prism-sans [animation:prism-scale-in_var(--prism-duration-normal)_var(--prism-easing-emphasized)] data-[state=closed]:[animation:prism-scale-out_var(--prism-duration-fast)_var(--prism-easing-exit)_forwards] data-[state=closed]:pointer-events-none focus-visible:[outline:var(--prism-focus-ring-width)_solid_var(--prism-color-ring)] focus-visible:[outline-offset:var(--prism-focus-ring-offset)]",
    "variants": {
      "size": {
        "sm": "[max-width:28rem]",
        "md": "[max-width:36rem]",
        "lg": "[max-width:48rem]"
      }
    }
  },
  "input": {
    "base": "box-border w-full min-h-(--prism-control-lg) px-prism-4 [border-width:0_0_1px_0] border-solid border-prism-border bg-transparent text-prism-fg [font-family:inherit] text-prism-md leading-prism-normal placeholder:text-prism-muted-fg focus-visible:[outline:none]",
    "variants": {}
  },
  "listbox": {
    "base": "overflow-y-auto p-prism-1",
    "variants": {}
  },
  "group": {
    "base": "py-prism-1",
    "variants": {}
  },
  "groupLabel": {
    "base": "py-prism-1 px-prism-2 text-prism-muted-fg text-prism-xs font-prism-medium",
    "variants": {}
  },
  "item": {
    "base": "flex items-center gap-prism-2 py-prism-2 px-prism-2 rounded-prism-sm text-prism-sm cursor-pointer select-none data-highlighted:bg-prism-muted aria-disabled:opacity-(--prism-opacity-disabled) aria-disabled:cursor-not-allowed",
    "variants": {}
  },
  "separator": {
    "base": "[height:1px] my-prism-1 [margin-inline:calc(-1_*_var(--prism-space-1))] bg-prism-border",
    "variants": {}
  },
  "empty": {
    "base": "p-prism-6 text-center text-prism-muted-fg text-prism-sm",
    "variants": {}
  }
});

export type { CommandItemData };

type Size = "sm" | "md" | "lg";

type ItemRecord = CollectionRecord<{
  /** DOM id of the option element. */
  id: string;
  value: string;
  textValue?: string;
  keywords?: readonly string[];
  disabled?: boolean;
  group?: string;
  /** The item's latest `onSelect`. */
  run: RefObject<(() => void) | undefined>;
}>;

interface PaletteContextValue {
  variants: { size: Size };
  label: string;
  listboxId: string;
  query: string;
  setQuery: (query: string) => void;
  hasResults: boolean;
  highlightedId: string | null;
  setHighlighted: (id: string) => void;
  isItemVisible: (id: string) => boolean;
  isGroupVisible: (group: string) => boolean;
  collection: Collection<ItemRecord>;
  choose: (id: string) => void;
  onInputKeyDown: (event: KeyboardEvent<HTMLInputElement>) => void;
  inputRef: RefObject<HTMLInputElement | null>;
}

const PaletteContext = createContext<PaletteContextValue | null>(null);
const GroupContext = createContext<string | undefined>(undefined);

function usePalette(part: string): PaletteContextValue {
  const ctx = useContext(PaletteContext);
  if (!ctx) throw new Error(`<${part}> must be used inside <CommandPalette>`);
  return ctx;
}

export interface CommandPaletteProps extends Omit<HTMLAttributes<HTMLDivElement>, "onSelect" | "role"> {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  /** Called with the chosen command's value (after the item's own `onSelect`). */
  onSelect?: (value: string) => void;
  /** Close after a command is chosen (default true). */
  closeOnSelect?: boolean;
  /** Accessible name of the dialog and list (default "Command palette"). */
  label?: string;
  /** Custom matcher; defaults to text + keywords, case- and accent-insensitive. */
  filter?: (item: CommandItemData, query: string) => boolean;
  /** Global shortcut that toggles the palette, e.g. "mod+k" (mod = Meta on macOS, Ctrl elsewhere). */
  shortcut?: string;
  size?: Size;
}

export const CommandPalette = forwardRef<HTMLDivElement, CommandPaletteProps>(
  (
    {
      open: openProp,
      defaultOpen = false,
      onOpenChange,
      onSelect,
      closeOnSelect = true,
      label = "Command palette",
      filter = matchesCommand,
      shortcut,
      size = "md",
      className,
      children,
      ...props
    },
    ref,
  ) => {
    const [open, setOpen] = useControllableState({
      value: openProp,
      defaultValue: defaultOpen,
      onChange: onOpenChange,
    });
    const [query, setQuery] = useState("");
    const [highlightedId, setHighlighted] = useState<string | null>(null);

    const baseId = useId();
    const listboxId = `${baseId}-listbox`;

    const contentRef = useRef<HTMLDivElement>(null);
    const portalRef = useRef<HTMLDivElement>(null);
    const inputRef = useRef<HTMLInputElement>(null);
    const composedRef = useComposedRefs(ref, contentRef);
    const variants = useMemo(() => ({ size }), [size]);

    // Items register through context, in any structure; kept in DOM order
    const collection = useCollection<ItemRecord>();
    const records = collection.items;
    const ordered = useMemo(() => filterCommands(records, query, filter), [records, query, filter]);
    const visibleIds = useMemo(() => new Set(ordered.map((r) => r.id)), [ordered]);
    const blank = !query.trim();

    const isItemVisible = useCallback(
      // Unregistered items (first render) show while the query is blank
      (id: string) => (collection.get(id) ? visibleIds.has(id) : blank),
      [collection, visibleIds, blank],
    );
    const isGroupVisible = useCallback(
      (group: string) => {
        const members = records.filter((r) => r.group === group);
        return members.length === 0 ? blank : members.some((r) => visibleIds.has(r.id));
      },
      [records, visibleIds, blank],
    );

    // Highlight the first enabled match whenever the matches change
    const orderedKey = ordered.map((r) => r.id).join("\n");
    useEffect(() => {
      const first = firstEnabled(ordered);
      setHighlighted(first === -1 ? null : ordered[first]!.id);
    }, [orderedKey]);

    // Start fresh each time the palette opens
    useIsomorphicLayoutEffect(() => {
      if (open) setQuery("");
    }, [open]);

    const setOpenRef = useRef(setOpen);
    setOpenRef.current = setOpen;
    const openRef = useRef(open);
    openRef.current = open;

    useEffect(() => {
      const content = contentRef.current;
      const portal = portalRef.current;
      if (!open || !content || !portal) return;
      const cleanups = [
        lockScroll(),
        hideOthers(portal),
        onDismiss({
          inside: () => [content],
          onDismiss: () => setOpenRef.current(false),
        }),
        trapFocus(content, { initialFocus: inputRef.current }),
      ];
      return () => {
        for (const cleanup of cleanups.reverse()) cleanup();
      };
    }, [open]);

    // Optional global shortcut toggles the palette
    useEffect(() => {
      if (!shortcut || typeof document === "undefined") return;
      const parsed = parseShortcut(shortcut);
      const apple = isApplePlatform(navigator.platform || navigator.userAgent);
      const handler = (event: globalThis.KeyboardEvent) => {
        if (event.defaultPrevented || !matchesShortcut(event, parsed, apple)) return;
        if (isTypingShortcut(parsed, event.target as HTMLElement | null)) return;
        event.preventDefault();
        setOpenRef.current(!openRef.current);
      };
      document.addEventListener("keydown", handler);
      return () => document.removeEventListener("keydown", handler);
    }, [shortcut]);

    // Keep the highlighted command in view
    useEffect(() => {
      if (highlightedId) document.getElementById(highlightedId)?.scrollIntoView?.({ block: "nearest" });
    }, [highlightedId]);

    const choose = (id: string) => {
      const record = collection.get(id);
      if (!record || record.disabled) return;
      record.run.current?.();
      onSelect?.(record.value);
      if (closeOnSelect) setOpen(false);
    };

    const onInputKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
      switch (event.key) {
        case "ArrowDown":
        case "ArrowUp":
        case "Home":
        case "End": {
          if (ordered.length === 0) return;
          event.preventDefault();
          const current = ordered.findIndex((r) => r.id === highlightedId);
          const next =
            current === -1 && (event.key === "ArrowDown" || event.key === "ArrowUp")
              ? firstEnabled(ordered, event.key === "ArrowUp")
              : nextIndex(event.key, Math.max(current, 0), ordered.length, {
                  orientation: "vertical",
                  isDisabled: (i) => !!ordered[i]!.disabled,
                });
          if (next !== null && next !== -1) setHighlighted(ordered[next]!.id);
          break;
        }
        case "Enter": {
          if (highlightedId && visibleIds.has(highlightedId)) {
            event.preventDefault();
            choose(highlightedId);
          }
          break;
        }
      }
    };

    const hasResults = ordered.length > 0;
    const ctx: PaletteContextValue = {
      variants,
      label,
      listboxId,
      query,
      setQuery,
      hasResults,
      highlightedId: highlightedId && visibleIds.has(highlightedId) ? highlightedId : null,
      setHighlighted,
      isItemVisible,
      isGroupVisible,
      collection,
      choose,
      onInputKeyDown,
      inputRef,
    };

    // Stays mounted, data-state="closed", while the exit animation plays
    const { present, state } = usePresence(open, contentRef);
    if (!present || typeof document === "undefined") return null;

    return createPortal(
      <PaletteContext.Provider value={ctx}>
        <div ref={portalRef}>
          <div
            aria-hidden="true"
            data-state={state}
            data-slot="command-palette-overlay"
            {...variantData(variants)}
            className={slotClass(slots, "overlay", variants)}
          />
          <div
            {...props}
            ref={composedRef}
            role="dialog"
            aria-modal={open ? "true" : undefined}
            aria-label={props["aria-labelledby"] ? undefined : (props["aria-label"] ?? label)}
            tabIndex={-1}
            data-state={state}
            data-slot="command-palette-content"
            {...variantData(variants)}
            className={slotClass(slots, "content", variants, className)}
          >
            {children}
          </div>
        </div>
      </PaletteContext.Provider>,
      document.body,
    );
  },
);
CommandPalette.displayName = "CommandPalette";

export type CommandInputProps = Omit<InputHTMLAttributes<HTMLInputElement>, "value" | "defaultValue" | "size">;

export const CommandInput = forwardRef<HTMLInputElement, CommandInputProps>(
  ({ placeholder = "Type a command or search…", className, onChange, onKeyDown, ...props }, ref) => {
    const ctx = usePalette("CommandInput");
    const composedRef = useComposedRefs(ref, ctx.inputRef);
    return (
      <input
        aria-label="Search commands"
        {...props}
        ref={composedRef}
        type="text"
        role="combobox"
        autoComplete="off"
        spellCheck={false}
        aria-autocomplete="list"
        aria-expanded={ctx.hasResults}
        aria-controls={ctx.listboxId}
        aria-activedescendant={ctx.highlightedId ?? undefined}
        placeholder={placeholder}
        value={ctx.query}
        data-slot="command-palette-input"
        {...variantData(ctx.variants)}
        className={slotClass(slots, "input", ctx.variants, className)}
        onChange={(event) => {
          onChange?.(event);
          if (!event.defaultPrevented) ctx.setQuery(event.target.value);
        }}
        onKeyDown={(event) => {
          onKeyDown?.(event);
          if (!event.defaultPrevented) ctx.onInputKeyDown(event);
        }}
      />
    );
  },
);
CommandInput.displayName = "CommandInput";

export type CommandListProps = HTMLAttributes<HTMLDivElement>;

/** The listbox. Stays mounted when nothing matches so `aria-controls` stays valid. */
export const CommandList = forwardRef<HTMLDivElement, CommandListProps>(({ className, ...props }, ref) => {
  const ctx = usePalette("CommandList");
  return (
    <div
      aria-label={props["aria-labelledby"] ? undefined : ctx.label}
      {...props}
      ref={ref}
      id={ctx.listboxId}
      role="listbox"
      data-slot="command-palette-listbox"
      {...variantData(ctx.variants)}
      className={slotClass(slots, "listbox", ctx.variants, className)}
    />
  );
});
CommandList.displayName = "CommandList";

export type CommandEmptyProps = HTMLAttributes<HTMLDivElement>;

/** Shown (as a live status) only when nothing matches. Place it next to `CommandList`, not inside. */
export const CommandEmpty = forwardRef<HTMLDivElement, CommandEmptyProps>(
  ({ className, children = "No results", ...props }, ref) => {
    const ctx = usePalette("CommandEmpty");
    if (ctx.hasResults) return null;
    return (
      <div
        {...props}
        ref={ref}
        role="status"
        data-slot="command-palette-empty"
        {...variantData(ctx.variants)}
        className={slotClass(slots, "empty", ctx.variants, className)}
      >
        {children}
      </div>
    );
  },
);
CommandEmpty.displayName = "CommandEmpty";

export interface CommandGroupProps extends HTMLAttributes<HTMLDivElement> {
  heading?: ReactNode;
}

/** A labelled group of items; not rendered while none of its items match. */
export const CommandGroup = forwardRef<HTMLDivElement, CommandGroupProps>(
  ({ heading, className, children, ...props }, ref) => {
    const ctx = usePalette("CommandGroup");
    const key = useId();
    const labelId = `${key}-label`;
    const content = <GroupContext.Provider value={key}>{children}</GroupContext.Provider>;
    // Items stay mounted (and registered) while the group is hidden
    if (!ctx.isGroupVisible(key)) return content;
    return (
      <div
        {...props}
        ref={ref}
        role="group"
        aria-labelledby={heading != null ? labelId : undefined}
        data-slot="command-palette-group"
        {...variantData(ctx.variants)}
        className={slotClass(slots, "group", ctx.variants, className)}
      >
        {heading != null && (
          <div
            id={labelId}
            data-slot="command-palette-group-label"
            {...variantData(ctx.variants)}
            className={slotClass(slots, "groupLabel", ctx.variants)}
          >
            {heading}
          </div>
        )}
        {content}
      </div>
    );
  },
);
CommandGroup.displayName = "CommandGroup";

export interface CommandItemProps extends Omit<HTMLAttributes<HTMLDivElement>, "onSelect"> {
  value: string;
  /** Searchable text; defaults to the rendered text content. */
  textValue?: string;
  /** Extra search terms (aliases, descriptions). */
  keywords?: readonly string[];
  disabled?: boolean;
  /** Runs when this command is chosen, before the palette's `onSelect`. */
  onSelect?: () => void;
}

export const CommandItem = forwardRef<HTMLDivElement, CommandItemProps>(
  (
    { value, textValue, keywords, disabled = false, onSelect, className, onClick, onMouseDown, onPointerMove, ...props },
    ref,
  ) => {
    const ctx = usePalette("CommandItem");
    const group = useContext(GroupContext);
    const id = useId();
    const elementRef = useRef<HTMLDivElement>(null);
    const composedRef = useComposedRefs(ref, elementRef);
    const onSelectRef = useRef(onSelect);
    onSelectRef.current = onSelect;

    // Text is remembered by value while the item is filtered out (not rendered)
    useCollectionItem(
      ctx.collection,
      { id, value, textValue, keywords, disabled, group, run: onSelectRef },
      elementRef,
    );

    if (!ctx.isItemVisible(id)) return null;
    const highlighted = ctx.highlightedId === id;

    return (
      <div
        {...props}
        ref={composedRef}
        id={id}
        role="option"
        aria-selected={highlighted}
        aria-disabled={disabled || undefined}
        data-highlighted={highlighted ? "" : undefined}
        data-value={value}
        data-slot="command-palette-item"
        {...variantData(ctx.variants)}
        className={slotClass(slots, "item", ctx.variants, className)}
        onMouseDown={(event) => {
          onMouseDown?.(event);
          // Keep focus in the input while clicking
          event.preventDefault();
        }}
        onPointerMove={(event) => {
          onPointerMove?.(event);
          if (!event.defaultPrevented && !disabled && !highlighted) ctx.setHighlighted(id);
        }}
        onClick={(event) => {
          onClick?.(event);
          if (!event.defaultPrevented) ctx.choose(id);
        }}
      />
    );
  },
);
CommandItem.displayName = "CommandItem";

export type CommandSeparatorProps = HTMLAttributes<HTMLDivElement>;

/** Decorative divider; hidden while searching. */
export const CommandSeparator = forwardRef<HTMLDivElement, CommandSeparatorProps>(({ className, ...props }, ref) => {
  const ctx = usePalette("CommandSeparator");
  if (ctx.query.trim()) return null;
  return (
    <div
      {...props}
      ref={ref}
      aria-hidden="true"
      data-slot="command-palette-separator"
      {...variantData(ctx.variants)}
      className={slotClass(slots, "separator", ctx.variants, className)}
    />
  );
});
CommandSeparator.displayName = "CommandSeparator";

// packages/core/components/command-palette/templates/vue/CommandPalette.vue
<script setup lang="ts">
import { computed, normalizeClass, onBeforeUnmount, onMounted, provide, ref, useAttrs, useId, watch } from "vue";
import { useCollection, useControllableState, usePresence } from "@defied-labs/prism-vue";
import { hideOthers, lockScroll, nextIndex, onDismiss, slotClass, trapFocus, variantData } from "@defied-labs/prism-core";
import {
  filterCommands,
  firstEnabled,
  isApplePlatform,
  isTypingShortcut,
  matchesCommand,
  matchesShortcut,
  parseShortcut,
  type CommandItem as CommandItemData,
} from "@defied-labs/prism-core/components/command-palette";
import { slots } from "./styles";
import { CommandPaletteKey, type ItemRecord, type Size } from "./context";

export interface CommandPaletteProps {
  open?: boolean;
  defaultOpen?: boolean;
  /** Close after a command is chosen (default true). */
  closeOnSelect?: boolean;
  /** Accessible name of the dialog and list (default "Command palette"). */
  label?: string;
  /** Custom matcher; defaults to text + keywords, case- and accent-insensitive. */
  filter?: (item: CommandItemData, query: string) => boolean;
  /** Global shortcut that toggles the palette, e.g. "mod+k" (mod = Meta on macOS, Ctrl elsewhere). */
  shortcut?: string;
  size?: Size;
}

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CommandPaletteProps>(), {
  open: undefined,
  defaultOpen: false,
  closeOnSelect: true,
  label: "Command palette",
  filter: undefined,
  shortcut: undefined,
  size: "md",
});
const emit = defineEmits<{
  "update:open": [open: boolean];
  openChange: [open: boolean];
  /** The chosen command's value (after the item's own `select`). */
  select: [value: string];
}>();

const attrs = useAttrs();
const open = useControllableState({
  value: () => props.open,
  defaultValue: props.defaultOpen,
  onChange: (next) => {
    emit("update:open", next);
    emit("openChange", next);
  },
});
const query = ref("");
const highlighted = ref<string | null>(null);

const listboxId = `${useId()}-listbox`;
const contentRef = ref<HTMLDivElement | null>(null);
const portalRef = ref<HTMLDivElement | null>(null);
const inputRef = ref<HTMLInputElement | null>(null);
// Stays mounted, data-state="closed", while the exit animation plays
const { present, state } = usePresence(() => open.value, contentRef);
const variants = computed(() => ({ size: props.size }));

// Items register through context, in any structure; kept in DOM order
const collection = useCollection<ItemRecord>();
const records = collection.items;
const ordered = computed(() => filterCommands(records.value, query.value, props.filter ?? matchesCommand));
const visibleIds = computed(() => new Set(ordered.value.map((r) => r.id)));
const blank = computed(() => !query.value.trim());

// Unregistered items (first render) show while the query is blank
const isItemVisible = (id: string) => {
  void records.value;
  return collection.get(id) ? visibleIds.value.has(id) : blank.value;
};
const isGroupVisible = (group: string) => {
  const members = records.value.filter((r) => r.group === group);
  return members.length === 0 ? blank.value : members.some((r) => visibleIds.value.has(r.id));
};

// Highlight the first enabled match whenever the matches change
watch(
  () => ordered.value.map((r) => r.id).join("\n"),
  () => {
    const first = firstEnabled(ordered.value);
    highlighted.value = first === -1 ? null : ordered.value[first]!.id;
  },
  { immediate: true },
);

// Start fresh each time the palette opens
watch(
  () => open.value,
  (isOpen) => {
    if (isOpen) query.value = "";
  },
  { flush: "sync" },
);

let cleanups: Array<() => void> = [];
function teardown() {
  for (const cleanup of cleanups.reverse()) cleanup();
  cleanups = [];
}
function activate(isOpen: boolean) {
  teardown();
  const content = contentRef.value;
  const portal = portalRef.value;
  if (!isOpen || !content || !portal) return;
  cleanups = [
    lockScroll(),
    hideOthers(portal),
    onDismiss({
      inside: () => [content],
      onDismiss: () => {
        open.value = false;
      },
    }),
    // Last, so focus moves in after the rest of the page is inert
    trapFocus(content, { initialFocus: inputRef.value }),
  ];
}
// After the DOM updates, like a React effect
onMounted(() => activate(open.value));
watch(() => open.value, activate, { flush: "post" });
onBeforeUnmount(teardown);

// Optional global shortcut toggles the palette
watch(
  () => props.shortcut,
  (shortcut, _, onCleanup) => {
    if (!shortcut || typeof document === "undefined") return;
    const parsed = parseShortcut(shortcut);
    const apple = isApplePlatform(navigator.platform || navigator.userAgent);
    const handler = (event: KeyboardEvent) => {
      if (event.defaultPrevented || !matchesShortcut(event, parsed, apple)) return;
      if (isTypingShortcut(parsed, event.target as HTMLElement | null)) return;
      event.preventDefault();
      open.value = !open.value;
    };
    document.addEventListener("keydown", handler);
    onCleanup(() => document.removeEventListener("keydown", handler));
  },
  { immediate: true },
);

// Keep the highlighted command in view
watch(
  highlighted,
  (id) => {
    if (id) document.getElementById(id)?.scrollIntoView?.({ block: "nearest" });
  },
  { flush: "post" },
);

function choose(id: string) {
  const record = collection.get(id);
  if (!record || record.disabled) return;
  record.run();
  emit("select", record.value);
  if (props.closeOnSelect) open.value = false;
}

function onInputKeyDown(event: KeyboardEvent) {
  const list = ordered.value;
  switch (event.key) {
    case "ArrowDown":
    case "ArrowUp":
    case "Home":
    case "End": {
      if (list.length === 0) return;
      event.preventDefault();
      const current = list.findIndex((r) => r.id === highlighted.value);
      const next =
        current === -1 && (event.key === "ArrowDown" || event.key === "ArrowUp")
          ? firstEnabled(list, event.key === "ArrowUp")
          : nextIndex(event.key, Math.max(current, 0), list.length, {
              orientation: "vertical",
              isDisabled: (i) => !!list[i]!.disabled,
            });
      if (next !== null && next !== -1) highlighted.value = list[next]!.id;
      break;
    }
    case "Enter": {
      const id = highlighted.value;
      if (id && visibleIds.value.has(id)) {
        event.preventDefault();
        choose(id);
      }
      break;
    }
  }
}

provide(CommandPaletteKey, {
  variants,
  label: computed(() => props.label),
  listboxId,
  query,
  hasResults: computed(() => ordered.value.length > 0),
  highlightedId: computed(() =>
    highlighted.value && visibleIds.value.has(highlighted.value) ? highlighted.value : null,
  ),
  setHighlighted: (id) => {
    highlighted.value = id;
  },
  isItemVisible,
  isGroupVisible,
  collection,
  choose,
  onInputKeyDown,
  inputRef,
});

// Read in the render, so attribute and state changes re-render the content
const contentAttrs = () => {
  const { class: className, ...rest } = attrs;
  return {
    ...rest,
    role: "dialog",
    "aria-modal": open.value ? ("true" as const) : undefined,
    "aria-label": attrs["aria-labelledby"]
      ? undefined
      : ((attrs["aria-label"] as string | undefined) ?? props.label),
    tabindex: -1,
    "data-state": state.value,
    "data-slot": "command-palette-content",
    ...variantData(variants.value),
    class: slotClass(slots, "content", variants.value, normalizeClass(className)),
  };
};

const overlayAttrs = () => ({
  "aria-hidden": "true" as const,
  "data-state": state.value,
  "data-slot": "command-palette-overlay",
  ...variantData(variants.value),
  class: slotClass(slots, "overlay", variants.value),
});
</script>

<template>
  <Teleport to="body">
    <div v-if="present" ref="portalRef">
      <div v-bind="overlayAttrs()" />
      <div ref="contentRef" v-bind="contentAttrs()"><slot /></div>
    </div>
  </Teleport>
</template>
