// apps/web/src/components/ui/Code.tsx
import { forwardRef, type HTMLAttributes } from "react";
import { slotClass, type StyleSlots } from "@defied-labs/prism-core";
import { tailwindSlots } from "@defied-labs/prism-core/tailwind";

export type CodeProps = HTMLAttributes<HTMLElement>;

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = tailwindSlots({
  "root": {
    "base": "font-prism-mono [font-size:0.85em] font-prism-medium [line-height:inherit] text-prism-fg bg-prism-muted [border-width:1px] border-solid border-prism-border rounded-prism-md [padding-block:0.1em] [padding-inline:0.4em] [white-space:break-spaces] [overflow-wrap:anywhere] [box-decoration-break:clone]",
    "variants": {}
  }
});

/** Inline code. */
export const Code = forwardRef<HTMLElement, CodeProps>(({ className, ...props }, ref) => (
  <code {...props} ref={ref} data-slot="code" className={slotClass(slots, "root", {}, className)} />
));

Code.displayName = "Code";

// apps/vue-demos/src/components/ui/code/Code.vue
<script setup lang="ts">
import { normalizeClass, useAttrs } from "vue";
import { slotClass, type StyleSlots } from "@defied-labs/prism-core";
import styles from "./Code.module.css";

/** Inline code. */
export type CodeProps = Record<string, never>;

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = { "root": { base: styles["root"], variants: {} } };

defineOptions({ inheritAttrs: false });

const attrs = useAttrs();
const variants = () => ({});

// Read in the render, so attribute changes re-render
const rootAttrs = () => {
  const { class: className, ...rest } = attrs;
  return {
    ...rest,
    "data-slot": "code",
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};
</script>

<template>
  <code v-bind="rootAttrs()"><slot /></code>
</template>
