// packages/core/components/code/templates/react/Code.tsx
import { forwardRef, type HTMLAttributes } from "react";
import { slotClass, type StyleSlots } from "@defied-labs/prism-core";

export type CodeProps = HTMLAttributes<HTMLElement>;

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

/** Inline code. */
export const Code = forwardRef<HTMLElement, CodeProps>(({ className, ...props }, ref) => (
  <code {...props} ref={ref} data-slot="code" className={slotClass(slots, "root", {}, className)} />
));

Code.displayName = "Code";

// apps/vue-demos/src/components/ui/code/Code.vue
<script setup lang="ts">
import { normalizeClass, useAttrs } from "vue";
import { slotClass, type StyleSlots } from "@defied-labs/prism-core";
import styles from "./Code.module.css";

/** Inline code. */
export type CodeProps = Record<string, never>;

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = { "root": { base: styles["root"], variants: {} } };

defineOptions({ inheritAttrs: false });

const attrs = useAttrs();
const variants = () => ({});

// Read in the render, so attribute changes re-render
const rootAttrs = () => {
  const { class: className, ...rest } = attrs;
  return {
    ...rest,
    "data-slot": "code",
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};
</script>

<template>
  <code v-bind="rootAttrs()"><slot /></code>
</template>
