// packages/core/components/box/templates/vue/Box.vue
<script setup lang="ts">
import { normalizeClass, useAttrs } from "vue";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";

/** Generic layout box. */
export type BoxElement =
  | "div"
  | "span"
  | "section"
  | "article"
  | "aside"
  | "header"
  | "footer"
  | "main"
  | "nav";

export interface BoxProps {
  /** Element to render. */
  as?: BoxElement;
  padding?: "none" | "sm" | "md" | "lg";
  background?: "none" | "subtle" | "muted";
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<BoxProps>(), { as: "div", padding: "none", background: "none" });
const attrs = useAttrs();
const variants = () => ({ padding: props.padding, background: props.background });

// Read in the render, so attribute changes re-render
const rootAttrs = () => {
  const { class: className, ...rest } = attrs;
  return {
    ...rest,
    "data-slot": "box",
    ...variantData(variants()),
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};
</script>

<template>
  <component :is="props.as" v-bind="rootAttrs()"><slot /></component>
</template>

// apps/web/src/components/ui/Box.tsx
import { forwardRef, type ElementType, type HTMLAttributes } from "react";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";
import { tailwindSlots } from "@defied-labs/prism-core/tailwind";

export type BoxElement =
  | "div"
  | "span"
  | "section"
  | "article"
  | "aside"
  | "header"
  | "footer"
  | "main"
  | "nav";

export interface BoxProps extends HTMLAttributes<HTMLElement> {
  /** Element to render. */
  as?: BoxElement;
  padding?: "none" | "sm" | "md" | "lg";
  background?: "none" | "subtle" | "muted";
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = tailwindSlots({
  "root": {
    "base": "box-border [min-width:0]",
    "variants": {
      "padding": {
        "none": "p-0",
        "sm": "p-prism-2",
        "md": "p-prism-4",
        "lg": "p-prism-6"
      },
      "background": {
        "none": "bg-transparent",
        "subtle": "bg-prism-bg-subtle text-prism-fg",
        "muted": "bg-prism-muted text-prism-fg"
      }
    }
  }
});

export const Box = forwardRef<HTMLElement, BoxProps>(
  ({ as = "div", padding = "none", background = "none", className, ...props }, ref) => {
    const Tag = as as ElementType;
    const variants = { padding, background };
    return (
      <Tag
        {...props}
        ref={ref}
        data-slot="box"
        {...variantData(variants)}
        className={slotClass(slots, "root", variants, className)}
      />
    );
  },
);

Box.displayName = "Box";
