// apps/vue-demos/src/components/ui/breadcrumb/Breadcrumb.vue
<script setup lang="ts">
import { Comment, Fragment, Text, nextTick, normalizeClass, provide, ref, useAttrs, useSlots, type VNode } from "vue";
import { slotClass, variantData } from "@defied-labs/prism-core";
import { slots } from "./styles";
import { BreadcrumbKey, type BreadcrumbSize } from "./context";

export interface BreadcrumbProps {
  size?: BreadcrumbSize;
  /** Separator between items (decorative, hidden from assistive tech). Default "/"; the `separator` slot overrides it. */
  separator?: string;
  /** Collapse middle items behind an ellipsis button when there are more items than this. */
  maxItems?: number;
  /** Items kept before the ellipsis when collapsed (default 1). */
  itemsBeforeCollapse?: number;
  /** Items kept after the ellipsis when collapsed (default 1). */
  itemsAfterCollapse?: number;
  /** Accessible name of the ellipsis button; receives the number of hidden items. */
  expandLabel?: (hidden: number) => string;
}

/**
 * `<nav aria-label="Breadcrumb"><ol>`: pass `BreadcrumbItem`s in the default
 * slot; separators are inserted between them.
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<BreadcrumbProps>(), {
  size: "md",
  separator: "/",
  maxItems: undefined,
  itemsBeforeCollapse: 1,
  itemsAfterCollapse: 1,
  expandLabel: (hidden: number) => `Show ${hidden} more`,
});

const attrs = useAttrs();
const slotsIn = useSlots();
const variants = () => ({ size: props.size });
provide(BreadcrumbKey, variants);

const expanded = ref(false);
const listRef = ref<HTMLOListElement | null>(null);

/** Element children of the default slot, fragments (v-for) unwrapped. */
function elements(nodes: VNode[] | undefined): VNode[] {
  const out: VNode[] = [];
  for (const node of nodes ?? []) {
    if (node.type === Comment || node.type === Text) continue;
    if (node.type === Fragment) out.push(...elements(node.children as VNode[]));
    else out.push(node);
  }
  return out;
}

type Entry = { key: string; node: VNode; ellipsis?: undefined } | { key: string; ellipsis: number };

// Called in the render, so slot and state changes re-render the list
function entries(): Entry[] {
  const items = elements(slotsIn.default?.());
  const toEntry = (node: VNode, index: number): Entry => ({ key: `item-${String(node.key ?? index)}`, node });
  const { maxItems, itemsBeforeCollapse: before, itemsAfterCollapse: after } = props;
  const collapse =
    !expanded.value && maxItems !== undefined && items.length > maxItems && before + after < items.length;
  if (!collapse) return items.map(toEntry);
  return [
    ...items.slice(0, before).map(toEntry),
    { key: "__ellipsis", ellipsis: items.length - before - after },
    ...items.slice(items.length - after).map((node, i) => toEntry(node, items.length - after + i)),
  ];
}

// Move focus to the first revealed item so keyboard users continue from there
async function expand() {
  expanded.value = true;
  await nextTick();
  const revealed = listRef.value?.querySelectorAll<HTMLElement>('[data-slot="breadcrumb-item"]')[
    props.itemsBeforeCollapse
  ];
  revealed?.querySelector<HTMLElement>("a[href], button, [tabindex]")?.focus();
}

const rootAttrs = () => {
  const { class: className, ...rest } = attrs;
  return {
    ...rest,
    "aria-label": (attrs["aria-label"] as string | undefined) ?? "Breadcrumb",
    "data-slot": "breadcrumb",
    ...variantData(variants()),
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};
const partAttrs = (slot: string) => ({
  "data-slot": `breadcrumb-${slot}`,
  ...variantData(variants()),
  class: slotClass(slots, slot, variants()),
});
</script>

<template>
  <nav v-bind="rootAttrs()">
    <ol ref="listRef" v-bind="partAttrs('list')">
      <template v-for="(entry, index) in entries()" :key="entry.key">
        <li v-if="index > 0" aria-hidden="true" v-bind="partAttrs('separator')">
          <slot name="separator">{{ props.separator }}</slot>
        </li>
        <li v-if="entry.ellipsis !== undefined" v-bind="partAttrs('item')">
          <button
            type="button"
            :aria-label="props.expandLabel(entry.ellipsis)"
            v-bind="partAttrs('ellipsis')"
            @click="expand"
          >
            <span aria-hidden="true">&hellip;</span>
          </button>
        </li>
        <component :is="entry.node" v-else />
      </template>
    </ol>
  </nav>
</template>

// apps/web/src/components/ui/Breadcrumb.tsx
import {
  Children,
  createContext,
  forwardRef,
  isValidElement,
  useContext,
  useEffect,
  useRef,
  useState,
  type AnchorHTMLAttributes,
  type HTMLAttributes,
  type LiHTMLAttributes,
  type ReactElement,
  type ReactNode,
} from "react";
import { Slot } from "@defied-labs/prism-react";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";
import { tailwindSlots } from "@defied-labs/prism-core/tailwind";

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = tailwindSlots({
  "root": {
    "base": "font-prism-sans text-prism-muted-fg leading-prism-normal",
    "variants": {
      "size": {
        "sm": "text-prism-xs",
        "md": "text-prism-sm"
      }
    }
  },
  "list": {
    "base": "flex flex-wrap items-center m-0 p-0 list-none",
    "variants": {
      "size": {
        "sm": "gap-prism-1",
        "md": "gap-prism-1-5"
      }
    }
  },
  "item": {
    "base": "inline-flex items-center",
    "variants": {}
  },
  "link": {
    "base": "text-inherit no-underline rounded-prism-sm [transition:color_var(--prism-duration-fast)_var(--prism-easing-standard)] not-aria-disabled:hover:text-prism-fg not-aria-disabled:hover:underline focus-visible:[outline:var(--prism-focus-ring-width)_solid_var(--prism-color-ring)] focus-visible:[outline-offset:var(--prism-focus-ring-offset)]",
    "variants": {}
  },
  "page": {
    "base": "text-prism-fg font-prism-medium",
    "variants": {}
  },
  "separator": {
    "base": "inline-flex items-center text-prism-muted-fg",
    "variants": {}
  },
  "ellipsis": {
    "base": "inline-flex items-center justify-center px-prism-1 [border-width:0] rounded-prism-sm bg-transparent text-inherit [font:inherit] cursor-pointer enabled:not-aria-disabled:hover:text-prism-fg focus-visible:[outline:var(--prism-focus-ring-width)_solid_var(--prism-color-ring)] focus-visible:[outline-offset:var(--prism-focus-ring-offset)]",
    "variants": {}
  }
});

type Size = "sm" | "md";

const BreadcrumbContext = createContext<{ size: Size } | null>(null);

function useVariants(part: string): { size: Size } {
  const context = useContext(BreadcrumbContext);
  if (!context) throw new Error(`<${part}> must be used inside <Breadcrumb>.`);
  return context;
}

export interface BreadcrumbProps extends HTMLAttributes<HTMLElement> {
  size?: Size;
  /** Separator between items (decorative, hidden from assistive tech). Default "/". */
  separator?: ReactNode;
  /** Collapse middle items behind an ellipsis button when there are more items than this. */
  maxItems?: number;
  /** Items kept before the ellipsis when collapsed (default 1). */
  itemsBeforeCollapse?: number;
  /** Items kept after the ellipsis when collapsed (default 1). */
  itemsAfterCollapse?: number;
  /** Accessible name of the ellipsis button; receives the number of hidden items. */
  expandLabel?: (hidden: number) => string;
}

/**
 * `<nav aria-label="Breadcrumb"><ol>`: pass `BreadcrumbItem`s as children;
 * separators are inserted between them.
 */
export const Breadcrumb = forwardRef<HTMLElement, BreadcrumbProps>(
  (
    {
      size = "md",
      separator = "/",
      maxItems,
      itemsBeforeCollapse = 1,
      itemsAfterCollapse = 1,
      expandLabel = (hidden) => `Show ${hidden} more`,
      className,
      children,
      "aria-label": ariaLabel = "Breadcrumb",
      ...props
    },
    ref,
  ) => {
    const variants = { size };
    const [expanded, setExpanded] = useState(false);
    const listRef = useRef<HTMLOListElement>(null);
    const items = Children.toArray(children).filter(isValidElement) as ReactElement[];

    const collapse =
      !expanded &&
      maxItems !== undefined &&
      items.length > maxItems &&
      itemsBeforeCollapse + itemsAfterCollapse < items.length;

    const hidden = collapse ? items.length - itemsBeforeCollapse - itemsAfterCollapse : 0;

    // Move focus to the first revealed item so keyboard users continue from there
    const focusRevealed = useRef(false);
    useEffect(() => {
      if (!expanded || !focusRevealed.current) return;
      focusRevealed.current = false;
      const revealed = listRef.current?.querySelectorAll<HTMLElement>(
        '[data-slot="breadcrumb-item"]',
      )[itemsBeforeCollapse];
      revealed?.querySelector<HTMLElement>("a[href], button, [tabindex]")?.focus();
    }, [expanded, itemsBeforeCollapse]);

    const expand = () => {
      focusRevealed.current = true;
      setExpanded(true);
    };

    const visible: ReactNode[] = collapse
      ? [
          ...items.slice(0, itemsBeforeCollapse),
          <li
            key="__ellipsis"
            data-slot="breadcrumb-item"
            {...variantData(variants)}
            className={slotClass(slots, "item", variants)}
          >
            <button
              type="button"
              aria-label={expandLabel(hidden)}
              data-slot="breadcrumb-ellipsis"
              {...variantData(variants)}
              className={slotClass(slots, "ellipsis", variants)}
              onClick={expand}
            >
              <span aria-hidden="true">…</span>
            </button>
          </li>,
          ...items.slice(items.length - itemsAfterCollapse),
        ]
      : items;

    return (
      <BreadcrumbContext.Provider value={variants}>
        <nav
          {...props}
          ref={ref}
          aria-label={ariaLabel}
          data-slot="breadcrumb"
          {...variantData(variants)}
          className={slotClass(slots, "root", variants, className)}
        >
          <ol
            ref={listRef}
            data-slot="breadcrumb-list"
            {...variantData(variants)}
            className={slotClass(slots, "list", variants)}
          >
            {visible.flatMap((item, index) =>
              index === 0
                ? [item]
                : [
                    <li
                      key={`__separator-${index}`}
                      aria-hidden="true"
                      data-slot="breadcrumb-separator"
                      {...variantData(variants)}
                      className={slotClass(slots, "separator", variants)}
                    >
                      {separator}
                    </li>,
                    item,
                  ],
            )}
          </ol>
        </nav>
      </BreadcrumbContext.Provider>
    );
  },
);
Breadcrumb.displayName = "Breadcrumb";

export const BreadcrumbItem = forwardRef<HTMLLIElement, LiHTMLAttributes<HTMLLIElement>>(
  ({ className, ...props }, ref) => {
    const variants = useVariants("BreadcrumbItem");
    return (
      <li
        {...props}
        ref={ref}
        data-slot="breadcrumb-item"
        {...variantData(variants)}
        className={slotClass(slots, "item", variants, className)}
      />
    );
  },
);
BreadcrumbItem.displayName = "BreadcrumbItem";

export interface BreadcrumbLinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  /** Render your own link (e.g. a router Link) instead of a plain <a>. */
  asChild?: boolean;
}

export const BreadcrumbLink = forwardRef<HTMLAnchorElement, BreadcrumbLinkProps>(
  ({ asChild = false, className, children, ...props }, ref) => {
    const variants = useVariants("BreadcrumbLink");
    const shared = {
      "data-slot": "breadcrumb-link",
      ...variantData(variants),
      className: slotClass(slots, "link", variants, className),
    };
    if (asChild) {
      return (
        <Slot {...(props as HTMLAttributes<HTMLElement>)} ref={ref} {...shared}>
          {children as ReactElement}
        </Slot>
      );
    }
    return (
      <a {...props} ref={ref} {...shared}>
        {children}
      </a>
    );
  },
);
BreadcrumbLink.displayName = "BreadcrumbLink";

/** The current page: not a link, marked aria-current="page". */
export const BreadcrumbPage = forwardRef<HTMLSpanElement, HTMLAttributes<HTMLSpanElement>>(
  ({ className, ...props }, ref) => {
    const variants = useVariants("BreadcrumbPage");
    return (
      <span
        {...props}
        ref={ref}
        aria-current="page"
        data-slot="breadcrumb-page"
        {...variantData(variants)}
        className={slotClass(slots, "page", variants, className)}
      />
    );
  },
);
BreadcrumbPage.displayName = "BreadcrumbPage";
