// apps/vue-demos/src/components/ui/divider/Divider.vue
<script setup lang="ts">
import { normalizeClass, useAttrs } from "vue";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";
import styles from "./Divider.module.css";

export interface DividerProps {
  orientation?: "horizontal" | "vertical";
  /** Purely visual: hidden from assistive technology. */
  decorative?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = { "root": { base: styles["root"], variants: {} } };

/**
 * Horizontal: an `<hr>` (implicit separator). Vertical: a `div` with
 * role="separator" and aria-orientation="vertical". Decorative dividers
 * carry no semantics.
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<DividerProps>(), {
  orientation: "horizontal",
  decorative: false,
});

const attrs = useAttrs();
const variants = () => ({ orientation: props.orientation });

// Read in the render, so attribute changes re-render the divider
const rootAttrs = () => {
  const { class: className, ...rest } = attrs;
  const semantics: Record<string, string> = props.decorative
    ? { role: "none", "aria-hidden": "true" }
    : props.orientation === "vertical"
      ? { role: "separator", "aria-orientation": "vertical" }
      : {};
  return {
    ...rest,
    ...semantics,
    "data-slot": "divider",
    ...variantData(variants()),
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};
</script>

<template>
  <div v-if="props.orientation === 'vertical'" v-bind="rootAttrs()" />
  <hr v-else v-bind="rootAttrs()" />
</template>

// apps/web/src/components/ui/Divider.tsx
import { forwardRef, type HTMLAttributes, type Ref } from "react";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";
import { tailwindSlots } from "@defied-labs/prism-core/tailwind";

export interface DividerProps extends HTMLAttributes<HTMLElement> {
  orientation?: "horizontal" | "vertical";
  /** Purely visual: hidden from assistive technology. */
  decorative?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = tailwindSlots({
  "root": {
    "base": "shrink-0 m-0 [border-width:0] bg-prism-border",
    "variants": {
      "orientation": {
        "horizontal": "w-full [height:1px] [align-self:auto]",
        "vertical": "[width:1px] [height:auto] [align-self:stretch]"
      }
    }
  }
});

/**
 * Horizontal: an `<hr>` (implicit separator). Vertical: a `div` with
 * role="separator" and aria-orientation="vertical". Decorative dividers
 * carry no semantics.
 */
export const Divider = forwardRef<HTMLElement, DividerProps>(
  ({ orientation = "horizontal", decorative = false, className, ...props }, ref) => {
    const variants = { orientation };
    const common = {
      "data-slot": "divider",
      ...variantData(variants),
      className: slotClass(slots, "root", variants, className),
    };

    if (orientation === "vertical") {
      return (
        <div
          {...props}
          ref={ref as Ref<HTMLDivElement>}
          {...(decorative
            ? { role: "none", "aria-hidden": true }
            : { role: "separator", "aria-orientation": "vertical" as const })}
          {...common}
        />
      );
    }
    return (
      <hr
        {...props}
        ref={ref as Ref<HTMLHRElement>}
        {...(decorative ? { role: "none", "aria-hidden": true } : {})}
        {...common}
      />
    );
  },
);

Divider.displayName = "Divider";
