// packages/core/components/link/templates/vue/Link.vue
<script setup lang="ts">
import { normalizeClass, useAttrs } from "vue";
import { Slot } from "@defied-labs/prism-vue";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";

export interface LinkProps {
  tone?: "primary" | "neutral" | "muted";
  underline?: "always" | "hover" | "none";
  /** Open in a new tab (rel="noopener noreferrer") and announce it. */
  external?: boolean;
  /** Text announced for external links. */
  externalLabel?: string;
  /** Merge onto the single child, e.g. a router `<RouterLink>`. */
  asChild?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<LinkProps>(), {
  tone: "primary",
  underline: "always",
  external: false,
  externalLabel: "(opens in a new tab)",
  asChild: false,
});

const attrs = useAttrs();
const variants = () => ({ tone: props.tone, underline: props.underline });

// Read in the render, so attribute changes re-render the link
const rootAttrs = () => {
  const { class: className, ...rest } = attrs;
  const rel = rest.rel as string | undefined;
  return {
    ...rest,
    ...(props.external
      ? {
          target: (rest.target as string | undefined) ?? "_blank",
          rel: [...new Set([...(rel?.split(/\s+/) ?? []), "noopener", "noreferrer"])]
            .filter(Boolean)
            .join(" "),
        }
      : {}),
    "data-slot": "link",
    ...variantData(variants()),
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};
</script>

<template>
  <Slot v-if="props.asChild" v-bind="rootAttrs()"><slot /></Slot>
  <a v-else v-bind="rootAttrs()"><slot /><template v-if="props.external">{{ " " }}<span data-part="external-hint">{{ props.externalLabel }}</span></template></a>
</template>

// packages/core/components/link/templates/react/Link.tsx
import { forwardRef, type AnchorHTMLAttributes, type ReactElement } from "react";
import { Slot } from "@defied-labs/prism-react";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";

export interface LinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  tone?: "primary" | "neutral" | "muted";
  underline?: "always" | "hover" | "none";
  /** Open in a new tab (rel="noopener noreferrer") and announce it. */
  external?: boolean;
  /** Text announced for external links. */
  externalLabel?: string;
  /** Merge onto the single child, e.g. a router `<Link>`. */
  asChild?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

export const Link = forwardRef<HTMLAnchorElement, LinkProps>(
  (
    {
      tone = "primary",
      underline = "always",
      external = false,
      externalLabel = "(opens in a new tab)",
      asChild = false,
      className,
      children,
      ...props
    },
    ref,
  ) => {
    const variants = { tone, underline };
    const own = {
      ...(external
        ? {
            target: props.target ?? "_blank",
            rel: [...new Set([...(props.rel?.split(/\s+/) ?? []), "noopener", "noreferrer"])]
              .filter(Boolean)
              .join(" "),
          }
        : {}),
      "data-slot": "link",
      ...variantData(variants),
      className: slotClass(slots, "root", variants, className),
    };
    const hint = external && (
      <span data-part="external-hint">{externalLabel}</span>
    );

    if (asChild) {
      return (
        <Slot {...props} {...own} ref={ref}>
          {children as ReactElement}
        </Slot>
      );
    }
    return (
      <a {...props} {...own} ref={ref}>
        {children}
        {hint && " "}
        {hint}
      </a>
    );
  },
);

Link.displayName = "Link";
