// packages/core/components/divider/templates/react/Divider.tsx
import { forwardRef, type HTMLAttributes, type Ref } from "react";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";

export interface DividerProps extends HTMLAttributes<HTMLElement> {
  orientation?: "horizontal" | "vertical";
  /** Purely visual: hidden from assistive technology. */
  decorative?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

/**
 * Horizontal: an `<hr>` (implicit separator). Vertical: a `div` with
 * role="separator" and aria-orientation="vertical". Decorative dividers
 * carry no semantics.
 */
export const Divider = forwardRef<HTMLElement, DividerProps>(
  ({ orientation = "horizontal", decorative = false, className, ...props }, ref) => {
    const variants = { orientation };
    const common = {
      "data-slot": "divider",
      ...variantData(variants),
      className: slotClass(slots, "root", variants, className),
    };

    if (orientation === "vertical") {
      return (
        <div
          {...props}
          ref={ref as Ref<HTMLDivElement>}
          {...(decorative
            ? { role: "none", "aria-hidden": true }
            : { role: "separator", "aria-orientation": "vertical" as const })}
          {...common}
        />
      );
    }
    return (
      <hr
        {...props}
        ref={ref as Ref<HTMLHRElement>}
        {...(decorative ? { role: "none", "aria-hidden": true } : {})}
        {...common}
      />
    );
  },
);

Divider.displayName = "Divider";

// packages/core/components/divider/templates/vue/Divider.vue
<script setup lang="ts">
import { normalizeClass, useAttrs } from "vue";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";

export interface DividerProps {
  orientation?: "horizontal" | "vertical";
  /** Purely visual: hidden from assistive technology. */
  decorative?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

/**
 * Horizontal: an `<hr>` (implicit separator). Vertical: a `div` with
 * role="separator" and aria-orientation="vertical". Decorative dividers
 * carry no semantics.
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<DividerProps>(), {
  orientation: "horizontal",
  decorative: false,
});

const attrs = useAttrs();
const variants = () => ({ orientation: props.orientation });

// Read in the render, so attribute changes re-render the divider
const rootAttrs = () => {
  const { class: className, ...rest } = attrs;
  const semantics: Record<string, string> = props.decorative
    ? { role: "none", "aria-hidden": "true" }
    : props.orientation === "vertical"
      ? { role: "separator", "aria-orientation": "vertical" }
      : {};
  return {
    ...rest,
    ...semantics,
    "data-slot": "divider",
    ...variantData(variants()),
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};
</script>

<template>
  <div v-if="props.orientation === 'vertical'" v-bind="rootAttrs()" />
  <hr v-else v-bind="rootAttrs()" />
</template>
