// packages/core/components/label/templates/react/Label.tsx
import { forwardRef, type LabelHTMLAttributes } from "react";
import { useField } from "@defied-labs/prism-react";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";

export interface LabelProps extends LabelHTMLAttributes<HTMLLabelElement> {
  size?: "sm" | "md";
  /** Shows a required marker. Defaults to the surrounding Field's `required`. */
  required?: boolean;
  /** Disabled look. Defaults to the surrounding Field's `disabled`. */
  disabled?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

/**
 * A form label. Inside a Field it labels the Field's control automatically
 * (id = field.labelId, htmlFor = field.controlId) unless given explicitly.
 * The required asterisk is visual only: the control carries `required`.
 */
export const Label = forwardRef<HTMLLabelElement, LabelProps>(
  ({ size = "md", required, disabled, id, htmlFor, className, children, ...props }, ref) => {
    const field = useField();
    const isRequired = required ?? field?.required ?? false;
    const variants = { size, dimmed: disabled ?? field?.disabled ?? false };
    return (
      <label
        {...props}
        ref={ref}
        id={id ?? field?.labelId}
        htmlFor={htmlFor ?? field?.controlId}
        data-slot="label"
        {...variantData(variants)}
        className={slotClass(slots, "root", variants, className)}
      >
        {children}
        {isRequired && (
          <span data-part="required-indicator" aria-hidden="true">
            *
          </span>
        )}
      </label>
    );
  },
);

Label.displayName = "Label";

// apps/vue-demos/src/components/ui/label/Label.vue
<script setup lang="ts">
import { normalizeClass, useAttrs } from "vue";
import { useField } from "@defied-labs/prism-vue";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";
import styles from "./Label.module.css";

export interface LabelProps {
  size?: "sm" | "md";
  /** Shows a required marker. Defaults to the surrounding Field's `required`. */
  required?: boolean;
  /** Disabled look. Defaults to the surrounding Field's `disabled`. */
  disabled?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = { "root": { base: styles["root"], variants: {} } };

/**
 * A form label. Inside a Field it labels the Field's control automatically
 * (id = field.labelId, for = field.controlId) unless given explicitly.
 * The required asterisk is visual only: the control carries `required`.
 */
defineOptions({ inheritAttrs: false });

// undefined (not false) when absent, so the Field's value applies
const props = withDefaults(defineProps<LabelProps>(), {
  size: "md",
  required: undefined,
  disabled: undefined,
});

const attrs = useAttrs();
const field = useField();

const isRequired = () => props.required ?? field?.required ?? false;
const variants = () => ({ size: props.size, dimmed: props.disabled ?? field?.disabled ?? false });

// Read in the render, so attribute and Field changes re-render the label
const rootAttrs = () => {
  const { class: className, id, for: htmlFor, htmlFor: reactFor, ...rest } = attrs;
  return {
    ...rest,
    id: (id as string | undefined) ?? field?.labelId,
    for: ((htmlFor ?? reactFor) as string | undefined) ?? field?.controlId,
    "data-slot": "label",
    ...variantData(variants()),
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};
</script>

<template>
  <label v-bind="rootAttrs()">
    <slot />
    <span v-if="isRequired()" data-part="required-indicator" aria-hidden="true">*</span>
  </label>
</template>
