// apps/vue-demos/src/components/ui/badge/Badge.vue
<script setup lang="ts">
import { normalizeClass, useAttrs } from "vue";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";
import styles from "./Badge.module.css";

/**
 * A small, non-interactive label. Color alone doesn't carry meaning: make
 * the text say the status ("Failed", not just a red dot).
 */
export interface BadgeProps {
  status?: "neutral" | "info" | "success" | "warning" | "danger";
  variant?: "subtle" | "solid" | "outline";
  size?: "sm" | "md";
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = { "root": { base: styles["root"], variants: {} } };

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<BadgeProps>(), {
  status: "neutral",
  variant: "subtle",
  size: "md",
});

const attrs = useAttrs();
const variants = () => ({ status: props.status, variant: props.variant, size: props.size });

// Read in the render, so attribute changes re-render the badge
const rootAttrs = () => {
  const { class: className, ...rest } = attrs;
  return {
    ...rest,
    "data-slot": "badge",
    ...variantData(variants()),
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};
</script>

<template>
  <span v-bind="rootAttrs()"><slot /></span>
</template>

// packages/core/components/badge/templates/react/Badge.tsx
import { forwardRef, type HTMLAttributes } from "react";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  status?: "neutral" | "info" | "success" | "warning" | "danger";
  variant?: "subtle" | "solid" | "outline";
  size?: "sm" | "md";
}

/**
 * A small, non-interactive label. Color alone doesn't carry meaning: make
 * the text say the status ("Failed", not just a red dot).
 */
export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(
  ({ status = "neutral", variant = "subtle", size = "md", className, ...props }, ref) => {
    const variants = { status, variant, size };
    return (
      <span
        {...props}
        ref={ref}
        data-slot="badge"
        {...variantData(variants)}
        className={slotClass(slots, "root", variants, className)}
      />
    );
  },
);
Badge.displayName = "Badge";

/** Decorative icon: `<Badge><BadgeIcon><CheckIcon /></BadgeIcon>Paid</Badge>` */
export function BadgeIcon({ children, ...props }: HTMLAttributes<HTMLSpanElement>) {
  return (
    <span {...props} data-part="icon" aria-hidden="true">
      {children}
    </span>
  );
}
