// packages/core/components/visually-hidden/templates/react/VisuallyHidden.tsx
import { forwardRef, type HTMLAttributes, type ReactElement } from "react";
import { Slot } from "@defied-labs/prism-react";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";

export interface VisuallyHiddenProps extends HTMLAttributes<HTMLElement> {
  /**
   * Reveal while focused. Combine with `asChild` so the focusable element
   * itself is hidden: `<VisuallyHidden focusable asChild><a href="#main">Skip to content</a></VisuallyHidden>`.
   */
  focusable?: boolean;
  /** Merge onto the single child element instead of rendering a span. */
  asChild?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

/** Content for screen readers only. */
export const VisuallyHidden = forwardRef<HTMLElement, VisuallyHiddenProps>(
  ({ focusable = false, asChild = false, className, children, ...props }, ref) => {
    const variants = { focusable };
    const own = {
      "data-slot": "visually-hidden",
      ...variantData(variants),
      className: slotClass(slots, "root", variants, className),
    };
    if (asChild) {
      return (
        <Slot {...props} {...own} ref={ref}>
          {children as ReactElement}
        </Slot>
      );
    }
    return (
      <span {...props} {...own} ref={ref}>
        {children}
      </span>
    );
  },
);

VisuallyHidden.displayName = "VisuallyHidden";

// packages/core/components/visually-hidden/templates/vue/VisuallyHidden.vue
<script setup lang="ts">
import { normalizeClass, useAttrs } from "vue";
import { Slot } from "@defied-labs/prism-vue";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";

/** Content for screen readers only. */
export interface VisuallyHiddenProps {
  /**
   * Reveal while focused. Combine with `asChild` so the focusable element
   * itself is hidden: `<VisuallyHidden focusable as-child><a href="#main">Skip to content</a></VisuallyHidden>`.
   */
  focusable?: boolean;
  /** Merge onto the single child element instead of rendering a span. */
  asChild?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<VisuallyHiddenProps>(), { focusable: false, asChild: false });
const attrs = useAttrs();
const variants = () => ({ focusable: props.focusable });

// Read in the render, so attribute changes re-render
const rootAttrs = () => {
  const { class: className, ...rest } = attrs;
  return {
    ...rest,
    "data-slot": "visually-hidden",
    ...variantData(variants()),
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};
</script>

<template>
  <Slot v-if="props.asChild" v-bind="rootAttrs()"><slot /></Slot>
  <span v-else v-bind="rootAttrs()"><slot /></span>
</template>
