// packages/core/components/input/templates/vue/Input.vue
<script setup lang="ts">
import { normalizeClass, useAttrs, watch } from "vue";
import { mergeFieldControlProps, useField, useMachine } from "@defied-prism/vue";
import {
  inputMachineDefinition,
  InputEvents,
} from "@defied-prism/core/components/input";
import { slotClass, variantData, type StyleSlots } from "@defied-prism/core";

export interface InputProps {
  variant?: "outlined" | "filled";
  size?: "sm" | "md" | "lg";
  fullWidth?: boolean;
  /** `v-model`; leave unset for an uncontrolled input. */
  modelValue?: string | number;
  id?: string;
  disabled?: boolean;
  required?: boolean;
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

defineOptions({ inheritAttrs: false });

// id/disabled/required stay undefined when unset, so a surrounding Field supplies them
const props = withDefaults(defineProps<InputProps>(), {
  variant: "outlined",
  size: "md",
  fullWidth: false,
  modelValue: undefined,
  id: undefined,
  disabled: undefined,
  required: undefined,
});

const emit = defineEmits<{ "update:modelValue": [value: string] }>();

const attrs = useAttrs();
// Labels, descriptions and errors belong to Field: inside one, it supplies
// id, aria-describedby, aria-invalid, disabled and required; explicit props win.
const field = useField();

// The DOM (or the caller, with v-model) owns the value; the machine only
// tracks focus / filled / disabled for data-state.
const { status, send } = useMachine(inputMachineDefinition);

const controlProps = () => {
  const { class: _class, ...rest } = attrs;
  return mergeFieldControlProps(field, {
    ...rest,
    id: props.id,
    disabled: props.disabled,
    required: props.required,
  } as Record<string, unknown> & { disabled?: boolean });
};

watch(
  () => controlProps().disabled ?? false,
  (disabled) => send(disabled ? InputEvents.disable() : InputEvents.enable()),
  { immediate: true },
);

const variants = () => ({ variant: props.variant, size: props.size, fullWidth: props.fullWidth });

// Read in the render, so attribute and Field changes re-render the input
const rootAttrs = () => {
  const merged = controlProps();
  return {
    ...merged,
    disabled: merged.disabled ?? false,
    ...variantData(variants()),
    "data-state": status.value,
    "data-slot": "input",
    class: slotClass(slots, "root", variants(), normalizeClass(attrs.class)),
  };
};

function onInput(event: Event) {
  const value = (event.target as HTMLInputElement).value;
  send(InputEvents.change(value));
  emit("update:modelValue", value);
}
</script>

<template>
  <input
    v-bind="rootAttrs()"
    :value="modelValue"
    @input="onInput"
    @focus="send(InputEvents.focus())"
    @blur="send(InputEvents.blur())"
  />
</template>

// packages/core/components/input/templates/react/Input.tsx
import {
  forwardRef,
  useEffect,
  type ChangeEvent,
  type FocusEvent,
  type InputHTMLAttributes,
} from "react";
import { useFieldControlProps, useMachine } from "@defied/prism-react";
import {
  inputMachineDefinition,
  InputEvents,
} from "@defied/prism-core/components/input";
import { slotClass, variantData, type StyleSlots } from "@defied/prism-core";

export interface InputProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, "size" | "aria-invalid"> {
  variant?: "outlined" | "filled";
  size?: "sm" | "md" | "lg";
  fullWidth?: boolean;
  "aria-invalid"?: boolean | "true" | "false";
}

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

export const Input = forwardRef<HTMLInputElement, InputProps>(
  (
    {
      variant = "outlined",
      size = "md",
      fullWidth = false,
      className,
      onChange,
      onBlur,
      onFocus,
      ...ownProps
    },
    ref,
  ) => {
    // Labels, descriptions and errors belong to Field: inside one, it
    // supplies id, aria-describedby, aria-invalid, disabled and required;
    // explicit props still win.
    const props = useFieldControlProps(ownProps);
    const disabled = props.disabled ?? false;

    // The DOM (or the caller, when controlled) owns the value; the machine
    // only tracks focus / filled / disabled for data-state.
    const { status, send } = useMachine(inputMachineDefinition);

    useEffect(() => {
      send(disabled ? InputEvents.disable() : InputEvents.enable());
    }, [disabled, send]);

    const variants = { variant, size, fullWidth };

    return (
      <input
        {...props}
        ref={ref}
        disabled={disabled}
        data-state={status}
        data-slot="input"
        {...variantData(variants)}
        className={slotClass(slots, "root", variants, className)}
        onChange={(event: ChangeEvent<HTMLInputElement>) => {
          send(InputEvents.change(event.target.value));
          onChange?.(event);
        }}
        onFocus={(event: FocusEvent<HTMLInputElement>) => {
          send(InputEvents.focus());
          onFocus?.(event);
        }}
        onBlur={(event: FocusEvent<HTMLInputElement>) => {
          send(InputEvents.blur());
          onBlur?.(event);
        }}
      />
    );
  },
);

Input.displayName = "Input";
