// packages/core/components/avatar/templates/react/Avatar.tsx
import {
  forwardRef,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type HTMLAttributes,
  type ImgHTMLAttributes,
  type ReactNode,
} from "react";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = {{STYLE_SLOTS}};

const useIsoLayoutEffect = typeof window === "undefined" ? useEffect : useLayoutEffect;

export type AvatarStatus = "loading" | "loaded" | "fallback";

/** "Ada Lovelace" -> "AL"; "Cher" -> "C". */
export function getInitials(name: string): string {
  const words = name.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return "";
  const first = Array.from(words[0]!)[0] ?? "";
  const last = words.length > 1 ? (Array.from(words[words.length - 1]!)[0] ?? "") : "";
  return first + last;
}

export interface AvatarProps extends Omit<HTMLAttributes<HTMLSpanElement>, "children"> {
  src?: string;
  /**
   * Required. The person's name: the avatar is exposed as `role="img"` with
   * this name, and the default initials come from it. Pass `""` when the
   * avatar is decorative (the name is printed next to it): it is then hidden
   * from assistive technology.
   */
  alt: string;
  /** Shown while the image loads or when it fails. Defaults to initials of `alt`. */
  fallback?: ReactNode;
  size?: "sm" | "md" | "lg" | "xl";
  shape?: "circle" | "square";
  /** Extra props for the `<img>`. */
  imageProps?: Omit<ImgHTMLAttributes<HTMLImageElement>, "src" | "alt">;
  onStatusChange?: (status: AvatarStatus) => void;
}

/**
 * The root carries the accessible name, so it is announced once whether the
 * image or the fallback is showing; the `<img>` and initials are presentational.
 */
export const Avatar = forwardRef<HTMLSpanElement, AvatarProps>(
  (
    { src, alt, fallback, size = "md", shape = "circle", imageProps, onStatusChange, className, ...props },
    ref,
  ) => {
    const variants = { size, shape };
    const [status, setStatus] = useState<AvatarStatus>(src ? "loading" : "fallback");
    const imgRef = useRef<HTMLImageElement>(null);
    const onStatusRef = useRef(onStatusChange);
    onStatusRef.current = onStatusChange;
    const statusRef = useRef(status);

    const update = (next: AvatarStatus) => {
      if (statusRef.current === next) return;
      statusRef.current = next;
      setStatus(next);
      onStatusRef.current?.(next);
    };

    // Reset on src change; pick up images that are already complete (cache).
    useIsoLayoutEffect(() => {
      if (!src) return update("fallback");
      const img = imgRef.current;
      update(img?.complete && img.naturalWidth > 0 ? "loaded" : "loading");
    }, [src]);

    const a11y = alt === "" ? { "aria-hidden": true as const } : { role: "img", "aria-label": alt };

    return (
      <span
        {...a11y}
        {...props}
        ref={ref}
        data-slot="avatar"
        data-state={status}
        {...variantData(variants)}
        className={slotClass(slots, "root", variants, className)}
      >
        {src && status !== "fallback" && (
          <img
            {...imageProps}
            key={src}
            ref={imgRef}
            src={src}
            alt=""
            hidden={status !== "loaded"}
            data-slot="avatar-image"
            {...variantData(variants)}
            className={slotClass(slots, "image", variants, imageProps?.className)}
            onLoad={(event) => {
              imageProps?.onLoad?.(event);
              update("loaded");
            }}
            onError={(event) => {
              imageProps?.onError?.(event);
              update("fallback");
            }}
          />
        )}
        {status !== "loaded" && (
          <span
            aria-hidden="true"
            data-slot="avatar-fallback"
            {...variantData(variants)}
            className={slotClass(slots, "fallback", variants)}
          >
            {fallback ?? getInitials(alt)}
          </span>
        )}
      </span>
    );
  },
);
Avatar.displayName = "Avatar";

// apps/vue-demos/src/components/ui/avatar/Avatar.vue
<script lang="ts">
import type { ImgHTMLAttributes } from "vue";

export type AvatarStatus = "loading" | "loaded" | "fallback";

/** "Ada Lovelace" -> "AL"; "Cher" -> "C". */
export function getInitials(name: string): string {
  const words = name.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return "";
  const first = Array.from(words[0]!)[0] ?? "";
  const last = words.length > 1 ? (Array.from(words[words.length - 1]!)[0] ?? "") : "";
  return first + last;
}

export interface AvatarProps {
  src?: string;
  /**
   * Required. The person's name: the avatar is exposed as `role="img"` with
   * this name, and the default initials come from it. Pass `""` when the
   * avatar is decorative (the name is printed next to it): it is then hidden
   * from assistive technology.
   */
  alt: string;
  /** Shown while the image loads or when it fails (or use the `fallback` slot). Defaults to initials of `alt`. */
  fallback?: string;
  size?: "sm" | "md" | "lg" | "xl";
  shape?: "circle" | "square";
  /** Extra attributes for the `<img>`. */
  imageProps?: Omit<ImgHTMLAttributes, "src" | "alt">;
}
</script>

<script setup lang="ts">
import { normalizeClass, onMounted, ref, useAttrs, watch } from "vue";
import { slotClass, variantData, type StyleSlots } from "@defied-labs/prism-core";
import styles from "./Avatar.module.css";

// Filled in by `prism add` from the component's recipe.
const slots: StyleSlots = { "root": { base: styles["root"], variants: {} }, "image": { base: styles["image"], variants: {} }, "fallback": { base: styles["fallback"], variants: {} } };

/**
 * The root carries the accessible name, so it is announced once whether the
 * image or the fallback is showing; the `<img>` and initials are presentational.
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<AvatarProps>(), {
  src: undefined,
  fallback: undefined,
  size: "md",
  shape: "circle",
  imageProps: undefined,
});
const emit = defineEmits<{ statusChange: [status: AvatarStatus] }>();

const attrs = useAttrs();
const variants = () => ({ size: props.size, shape: props.shape });

const status = ref<AvatarStatus>(props.src ? "loading" : "fallback");
const imgRef = ref<HTMLImageElement | null>(null);

function update(next: AvatarStatus) {
  if (status.value === next) return;
  status.value = next;
  emit("statusChange", next);
}

// Reset on src change; pick up images that are already complete (cache).
function sync() {
  if (!props.src) return update("fallback");
  const img = imgRef.value;
  update(img?.complete && img.naturalWidth > 0 ? "loaded" : "loading");
}
onMounted(sync);
watch(() => props.src, sync, { flush: "post" });

// Read in the render, so attribute changes re-render the avatar
const rootAttrs = () => {
  const { class: className, ...rest } = attrs;
  const a11y = props.alt === "" ? { "aria-hidden": "true" as const } : { role: "img", "aria-label": props.alt };
  return {
    ...a11y,
    ...rest,
    "data-slot": "avatar",
    "data-state": status.value,
    ...variantData(variants()),
    class: slotClass(slots, "root", variants(), normalizeClass(className)),
  };
};

const imageAttrs = () => {
  const { class: className, onLoad, onError, ...rest } = (props.imageProps ?? {}) as Record<string, unknown>;
  return {
    ...rest,
    src: props.src,
    alt: "",
    hidden: status.value !== "loaded",
    "data-slot": "avatar-image",
    ...variantData(variants()),
    class: slotClass(slots, "image", variants(), normalizeClass(className)),
    onLoad: (event: Event) => {
      (onLoad as ((event: Event) => void) | undefined)?.(event);
      update("loaded");
    },
    onError: (event: Event) => {
      (onError as ((event: Event) => void) | undefined)?.(event);
      update("fallback");
    },
  };
};

const fallbackAttrs = () => ({
  "aria-hidden": "true" as const,
  "data-slot": "avatar-fallback",
  ...variantData(variants()),
  class: slotClass(slots, "fallback", variants()),
});
</script>

<template>
  <span v-bind="rootAttrs()">
    <img v-if="props.src && status !== 'fallback'" :key="props.src" ref="imgRef" v-bind="imageAttrs()" />
    <span v-if="status !== 'loaded'" v-bind="fallbackAttrs()">
      <slot name="fallback">{{ props.fallback ?? getInitials(props.alt) }}</slot>
    </span>
  </span>
</template>
